### PR TITLE
add signature for testing

### PR DESCRIPTION
**Pull request by rebornishard**
edit example

### CODE REVIEW

**Review by tpenaranda — CHANGES_REQUESTED** [review]
You're totally right @rebornishard, thank you so much!. But looks like 'Signature' should be the second paramater. What do you think if we use the same example as on CryptoJS docs [https://cryptojs.gitbook.io/docs/#hmac]

`var hash = CryptoJS.HmacSHA1("Message", "Secret Passphrase");`

**Comment by rebornishard** [comment]
> You're totally right @rebornishard, thank you so much!. But looks like 'Signature' should be the second paramater. What do you think if we use the same example as on CryptoJS docs [https://cryptojs.gitbook.io/docs/#hmac]
> 
> `var hash = CryptoJS.HmacSHA1("Message", "Secret Passphrase");`

Lol, i just did this before sleep, glad u review it,
so it's 
CryptoJS.HmacSHA1("Message", "Key");
let me repair this pull
thanks for guiding me

**Comment by rebornishard** [comment]
This should do it

**Comment by tpenaranda** [comment]
Thanks @rebornishard

**Pull request merged**
